apiVersion: v1
kind: Namespace
metadata:
  name: simon_marin_ma-application-monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simon_marin_ma-application-monitoring
  labels:
    app: simon_marin_ma-application-monitoring
  namespace: simon_marin_ma-application-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simon_marin_ma-application-monitoring
  template:
    metadata:
      labels:
        app: simon_marin_ma-application-monitoring
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: simon_marin_ma-application-monitoring
        image: hello-world:latest #Workflows will update this image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simon_marin_ma-application-monitoring
  labels:
    app: simon_marin_ma-application-monitoring
  namespace: simon_marin_ma-application-monitoring
spec:
  selector:
    app: simon_marin_ma-application-monitoring
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simon_marin_ma-application-monitoring-ingress
  namespace: simon_marin_ma-application-monitoring
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: simon_marin_ma-application.prueba-piloto-stack.eci-idp.click
      http:
        paths:
          - path: /.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: simon_marin_ma-application-monitoring
                port:
                  number: 80